# Generated by Django 5.0.6 on 2024-06-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_dialogue',
            new_name='dialogue',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id_user_recipient',
            new_name='user_recipient',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id_user_sender',
            new_name='user_sender',
        ),
    ]
