# Generated by Django 5.0.6 on 2024-06-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_id_dialogue_message_dialogue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='avatar',
        ),
    ]
