# Generated by Django 5.0.6 on 2024-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.TextField(choices=[('FILE', 'file'), ('IMAGE', 'image'), ('VIDEO', 'video')]),
        ),
    ]
