# Generated by Django 5.0.6 on 2024-06-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_attachment_attachment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
