# Generated by Django 5.0.6 on 2024-06-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialogue',
            table='dialogue',
        ),
    ]
