# Generated by Django 5.0.6 on 2024-06-06 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_alter_dialogue_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='is_dialogue',
            new_name='is_pinned',
        ),
        migrations.CreateModel(
            name='DialogueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.dialogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
