# Generated by Django 5.0.6 on 2024-06-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_rename_is_dialogue_dialogue_is_pinned_dialogueuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialogueuser',
            table='dialogue_user',
        ),
    ]
