# Generated by Django 5.0.6 on 2024-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_alter_dialogueuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
