# Generated by Django 5.0.6 on 2024-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_dialogue_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='avatar',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
