# Generated by Django 5.0.6 on 2024-06-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_remove_dialogue_is_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogueuser',
            name='user',
        ),
        migrations.AddField(
            model_name='dialogueuser',
            name='user_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_dialogue_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogueuser',
            name='user_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_dialogue_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
