# Generated by Django 5.0.6 on 2024-06-10 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0008_remove_dialogueuser_user_dialogueuser_user_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialogueuser',
            unique_together={('user_sender', 'user_recipient')},
        ),
    ]
