# Generated by Django 5.0.6 on 2024-06-04 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 7, 52, 32, 55285, tzinfo=datetime.timezone.utc), verbose_name='date_registration'),
        ),
    ]
