# Generated by Django 5.0.6 on 2024-06-04 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 13, 8, 7, 554008, tzinfo=datetime.timezone.utc), verbose_name='date_registration'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
