# Generated by Django 5.0.6 on 2024-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_date_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='обычная аватарка пользователя', max_length=255),
        ),
    ]
