# Generated by Django 5.0.6 on 2024-06-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_avatar_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='http://localhost:3000/static/images/default_avatar.jpg', max_length=255),
        ),
    ]
