# Generated by Django 5.0.6 on 2024-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('REJECTED', 'rejected'), ('DELETED', 'deleted')], default='ACCEPTED'),
        ),
    ]
