# Generated by Django 5.0.6 on 2024-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
